---
- hosts: icinga_master  
  become: true
  tasks:
    - ansible.builtin.include_role:
        name: tbauriedel.influxdb2.repos

    - ansible.builtin.include_role:
        name: tbauriedel.influxdb2.influxdb2

    - ansible.builtin.include_role:
        name: tbauriedel.gographite.gocarbon

    - ansible.builtin.include_role:
        name: tbauriedel.gographite.carbonapi

    - ansible.builtin.include_role:
        name: geerlingguy.apache

    - ansible.builtin.include_role:
        name: geerlingguy.mysql

    - ansible.builtin.include_role:
        name: icinga.icinga.repos

    - ansible.builtin.include_role:
        name: icinga.icinga.icingadb_redis

    - ansible.builtin.include_role:
        name: icinga.icinga.icingadb
    
    - ansible.builtin.include_role:
        name: icinga.icinga.icinga2

    # Icinga 2 needs to be finished before installing director
    - meta: flush_handlers

    - ansible.builtin.include_role:
        name: icinga.icinga.icingaweb2
