---
grafana_ini:
  security:
    admin_user: admin
    admin_password: admin
    allow_embedding: true
  auth:
    anonymous:
      enabled: true
      org_role: Viewer
  log:
    mode: syslog
    level: warn
