---
icingaweb2_db:
  type: mysql
  name: icingaweb2
  host: 127.0.0.1
  user: admin
  password: admin
icingaweb2_db_import_schema: true
icingaweb2_resources:
  icingadb:
    type: db
    db: mysql
    host: localhost
    dbname: icingadb
    username: admin
    password: admin
    use_ssl: 0
    charset: utf8
  director:
    type: db
    db: mysql
    host: localhost
    dbname: director
    username: admin
    password: admin
    use_ssl: 0
icingaweb2_modules:
  director:
    enabled: true
    source: package
    import_schema: true
    run_kickstart: true
    kickstart:
      config:
        endpoint: "{{ ansible_fqdn }}"
        host: 127.0.0.1
        username: admin
        password: admin
    config:
      db:
        resource: director
  icingadb:
    enabled: true
    source: package
    commandtransports:
      instance01:
        transport: api
        host: 127.0.0.1
        username: admin
        password: admin
    config:
      icingadb:
        resource: icingadb
      redis:
        tls: '0'
    redis:
      redis1:
        host: "127.0.0.1"
        password: redis-pass

icingaweb2_admin_username: icinga
icingaweb2_admin_password: icinga

icingaweb2_config:
  global:
    show_stacktraces: 1
    show_application_state_messages: 1
    config_resource: icingaweb2_db
    module_path: /usr/share/icingaweb2/modules
  logging:
    log: syslog
    level: ERROR
    application: icingaweb2
    facility: user
  themes:
    default: Icinga